spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_sell?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: myuser
  application:
    name: order
env:
   github - dev4

person:
  name: timo牛
  age: 20
